  
# DESCRIPTION: GitLab CI/CD for libRetro (NOT FOR GitLab-proper)

##############################################################################
################################# BOILERPLATE ################################
##############################################################################

# Core definitions
.core-defs:
  variables:
    CORENAME: boom3
    MAKEFILE_PATH: neo
    MAKEFILE: Makefile
    
.core-defs-xp:
  variables:
    CORENAME: boom3_xp
    MAKEFILE_PATH: neo
    MAKEFILE: Makefile
    D3XP: 1

# Inclusion templates, required for the build to work
include:
  ################################## DESKTOPS ################################
  # Windows 64-bit
  - project: 'libretro-infrastructure/ci-templates'
    file: '/windows-x64-mingw.yml'
    
  # Windows 32-bit
  - project: 'libretro-infrastructure/ci-templates'
    file: '/windows-i686-mingw.yml'
    
  # Linux 64-bit
  - project: 'libretro-infrastructure/ci-templates'
    file: '/linux-x64.yml'

  # Linux 32-bit
  - project: 'libretro-infrastructure/ci-templates'
    file: '/linux-i686.yml'

 ################################## CONSOLES ################################
 # Nintendo Switch
  - project: 'libretro-infrastructure/ci-templates'
    file: '/libnx-static.yml'

# Stages for building
stages:
  - build-prepare
  - build-shared
  - build-static

##############################################################################
#################################### STAGES ##################################
##############################################################################
#
################################### DESKTOPS #################################
# Windows 64-bit
libretro-build-windows-x64:
  extends:
    - .libretro-windows-x64-mingw-make-default
    - .core-defs

libretro-build-windows-x64-xp:
  extends:
    - .libretro-windows-x64-mingw-make-default
    - .core-defs-xp

# Windows 32-bit
libretro-build-windows-i686:
  extends:
    - .libretro-windows-i686-mingw-make-default
    - .core-defs

libretro-build-windows-i686-xp:
  extends:
    - .libretro-windows-i686-mingw-make-default
    - .core-defs-xp

# Linux 64-bit
libretro-build-linux-x64:
  extends:
    - .libretro-linux-x64-make-default
    - .core-defs
    
libretro-build-linux-x64-xp:
  extends:
    - .libretro-linux-x64-make-default
    - .core-defs-xp

# Linux 32-bit
libretro-build-linux-i686:
  extends:
    - .libretro-linux-i686-make-default
    - .core-defs

################################### CONSOLES #################################
# Nintendo Switch
libretro-build-libnx-aarch64:
  extends:
    - .libretro-libnx-static-retroarch-master
    - .core-defs

libretro-build-libnx-aarch64-xp:
  extends:
    - .libretro-libnx-static-retroarch-master
    - .core-defs-xp
