#!/usr/bin/env python3
# gen_kemar_hrir.py - bake the MIT KEMAR compact HRIR set into a C header
# for the boom3 libretro core's built-in HRTF renderer (s_HRTF).
#
# Input: the extracted "compact" measurements,
#   https://sound.media.mit.edu/resources/KEMAR/compact.zip
#   (elev-40 .. elev90 directories of stereo 128-tap 16-bit 44.1 kHz WAVs,
#    filenames H{elev}e{azim}a.wav, azimuths 0..~180 on irregular grids;
#    the other hemisphere is obtained by mirroring with the ears swapped)
#
# The data is Copyright 1994 by the MIT Media Laboratory, provided free
# with no restrictions on use, provided the authors are cited:
#   Bill Gardner and Keith Martin, "HRTF Measurements of a KEMAR
#   Dummy-Head Microphone", MIT Media Lab Perceptual Computing
#   Technical Report #280, 1994.
#
# Normalization: all coefficients are scaled by one global factor so the
# largest spectral magnitude over every direction and ear is exactly
# 32767/32768 at Q15 - i.e. unity peak gain. The worst-case time-domain
# gain (max over directions of sum(|h|)) is reported and emitted as a
# constant so the mixer can document its accumulator bounds against it.
#
# Usage: gen_kemar_hrir.py <extracted-compact-dir> <output-header>

import sys, os, glob, re, wave, struct
import numpy as np

src, out = sys.argv[1], sys.argv[2]

elevs = []
for d in sorted(glob.glob(os.path.join(src, 'elev*')),
                key=lambda p: int(re.search(r'elev(-?\d+)$', p).group(1))):
    e = int(re.search(r'elev(-?\d+)$', d).group(1))
    rows = []
    for f in glob.glob(os.path.join(d, '*.wav')):
        az = int(re.search(r'e(\d+)a\.wav$', f).group(1))
        w = wave.open(f, 'rb')
        assert (w.getnchannels(), w.getframerate(),
                w.getnframes(), w.getsampwidth()) == (2, 44100, 128, 2), f
        raw = np.frombuffer(w.readframes(128), dtype='<i2').reshape(128, 2)
        rows.append((az, raw.astype(np.float64)))
    rows.sort()
    elevs.append((e, rows))

# global spectral-peak normalization
peak = 0.0
for e, rows in elevs:
    for az, h in rows:
        H = np.abs(np.fft.rfft(h, n=512, axis=0))
        peak = max(peak, H.max())
scale = (32767.0 / 32768.0) * 32768.0 / peak

dirs = []           # flat list of (128,2) int16 arrays
elev_deg = []
elev_az = []        # per elevation: list of (az_deg, dir_index)
sumabs_max = 0.0
for e, rows in elevs:
    elev_deg.append(e)
    ring = []
    for az, h in rows:
        q = np.clip(np.rint(h * scale), -32768, 32767).astype(np.int16)
        sumabs_max = max(sumabs_max, np.abs(q.astype(np.float64)).sum(axis=0).max())
        ring.append((az, len(dirs)))
        dirs.append(q)
    elev_az.append(ring)

# full-circle rings: measured entries plus mirrored entries (ear swap),
# deduplicating az 0 and az 180 which mirror onto themselves
rings = []
for ring in elev_az:
    full = [(az, idx, 0) for az, idx in ring]
    for az, idx in ring:
        m = (360 - az) % 360
        if all(m != a for a, _, _ in full):
            full.append((m, idx, 1))
    full.sort()
    rings.append(full)

with open(out, 'w') as f:
    W = f.write
    W("/* Generated by tools/hrtf/gen_kemar_hrir.py - DO NOT EDIT.\n")
    W(" *\n")
    W(" * MIT KEMAR compact HRIR set, 128 taps, 44100 Hz, Q15, normalized\n")
    W(" * to unity spectral peak gain over all directions and ears.\n")
    W(" *\n")
    W(" * The data is Copyright 1994 by the MIT Media Laboratory. It is\n")
    W(" * provided free with no restrictions on use, provided the authors\n")
    W(" * are cited when the data is used in any research or commercial\n")
    W(" * application:\n")
    W(" *   Bill Gardner and Keith Martin, \"HRTF Measurements of a KEMAR\n")
    W(" *   Dummy-Head Microphone\", MIT Media Lab Perceptual Computing\n")
    W(" *   Technical Report #280, 1994.\n")
    W(" *   https://sound.media.mit.edu/resources/KEMAR.html\n")
    W(" */\n\n")
    W("#ifndef __SND_HRIR_KEMAR_H__\n#define __SND_HRIR_KEMAR_H__\n\n")
    W("#define SND_HRIR_RATE      44100\n")
    W("#define SND_HRIR_TAPS      128\n")
    W("#define SND_HRIR_DIRS      %d\n" % len(dirs))
    W("#define SND_HRIR_ELEVS     %d\n" % len(elev_deg))
    W("#define SND_HRIR_ELEV_MIN  (%d)\n" % elev_deg[0])
    W("#define SND_HRIR_ELEV_STEP 10\n")
    W("/* worst-case time-domain gain: max over directions of sum(|h|),\n")
    W("   in Q15 units - the mixer's accumulator bound derives from this */\n")
    W("#define SND_HRIR_MAX_SUMABS_Q15 %d\n\n" % int(sumabs_max))
    W("/* full-circle azimuth rings per elevation (measured 0..180 plus\n")
    W("   mirrored entries): ascending az in degrees, HRIR index, and\n")
    W("   whether the ears are swapped for that entry */\n")
    W("typedef struct { short azDeg; short dirIndex; short swap; } sndHrirRingEntry_t;\n\n")
    W("static const int sndHrirRingLen[SND_HRIR_ELEVS] = { %s };\n\n"
      % ", ".join(str(len(r)) for r in rings))
    for i, r in enumerate(rings):
        W("static const sndHrirRingEntry_t sndHrirRing%d[%d] = {\n" % (i, len(r)))
        for az, idx, sw in r:
            W("\t{ %d, %d, %d },\n" % (az, idx, sw))
        W("};\n")
    W("\nstatic const sndHrirRingEntry_t * const sndHrirRings[SND_HRIR_ELEVS] = { %s };\n\n"
      % ", ".join("sndHrirRing%d" % i for i in range(len(rings))))
    W("/* [dir][tap][ear], ear 0 = left */\n")
    W("static const short sndHrirData[SND_HRIR_DIRS][SND_HRIR_TAPS][2] = {\n")
    for q in dirs:
        W("{" + ",".join("{%d,%d}" % (a, b) for a, b in q) + "},\n")
    W("};\n\n#endif /* !__SND_HRIR_KEMAR_H__ */\n")

print("dirs=%d peak_spectral=%.1f scale=%.6f max_sumabs=%.0f (%.2fx unity)"
      % (len(dirs), peak, scale, sumabs_max, sumabs_max / 32768.0))
